version: '3.4'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    volumes:
        - './backend:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DEV_DB_URL=db:5432/dev
      - TEST_DB_URL=db:5432/dev
      - PRODUCT_DB_URL=db:5432/dev
      - SECRET_KEY=my_precious
    depends_on:
      - db
    links:
      - db

  db:
    container_name: db
    build:
      context: ./backend/project/database
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

